name: verify_user_in_organization
description: Verify user in organization
inputs:
  username:
    description: "The id of the user"
    required: true
  token:
    description: "Token to access Github API"
    required: true
runs:
  using: composite
  steps:
    - name: Verify user in organization
      id: verify_user_in_organization
      shell: bash
      run: |
        echo "Verifying user's organization..."
        response=$(curl -s -L \
            -w "%{http_code}" \
            -o /dev/null -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ inputs.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/orgs/binary-com/memberships/${{inputs.username}}")
            
        if [ $response != "200" ]; then
            echo "User is not a member of binary-com organization."
            exit 1
        else
            echo "User is a member of binary-com organization."
        fi
