name: post_preview_build_comment
description: Post preview build comment
inputs:
  issue_number:
    description: "PR number"
    required: true
  head_sha:
    description: "SHA of the commit"
    required: true
outputs:
  check_run_id:
    description: "Id of the created check"
    value: ${{ steps.create_build_check.outputs.check_run_id }}
runs:
  using: composite
  steps:
    - name: "Post build comment"
      id: post_build_comment
      uses: actions/github-script@ffc2c79a5b2490bd33e0a41c1de74b877714d736
      with:
        github-token: ${{ github.token }}
        script: |
          const action_url = "${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
          const comment = [
              '| Name | Result |',
              '| :--- | :------ |',
              `| **Build status**  | Building 🔨 |`,
              `| **Action URL**  | [Visit Action](${action_url}) |`,
              ''
            ].join('\n')
          core.setOutput("comment", comment);
    - name: "Post Cloudflare Pages Preview comment"
      uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31
      with:
        header: Cloudflare Pages Preview Comment
        number: ${{ inputs.issue_number }}
        message: ${{steps.post_build_comment.outputs.comment}}
        recreate: true

    - name: "Create a build check"
      id: create_build_check
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
      env:
        HEAD_SHA: ${{ inputs.head_sha }}
      with:
        github-token: ${{ github.token }}
        script: |
          const action_url = "${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
          const check = await github.rest.checks.create({
              ...context.repo,
              name: "Generate preview link",
              head_sha: process.env.HEAD_SHA,
              details_url: action_url,
              status: "in_progress",
              output: {
                title: "Generate preview link",
                summary: `Preview link creation is in progress. Build URL: - ${action_url}`,
              },
          });
          core.setOutput("check_run_id", check.data.id);
