name: npm_install
description: Install npm packages
runs:
  using: composite
  steps:
    - name: Cache dependencies
      id: cache-node-modules
      uses: actions/cache/restore@v3
      with:
        key: v1-deps-{{ hashFiles("package-lock.json") }}
        path: node_modules
    - name: Install npm dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
    - name: save_cache
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        path: node_modules
        key: v1-deps-{{ hashFiles("package-lock.json") }}
